### ISSUE TITLE
Some users dont get noticed by commands

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#95]
i.e `@instig#8737`

**Comment by stelar7** [comment]
Seems to be fixed by 864843febdd52daff0695e11d355c0de06069bc8, but we should check the entire codebase and replace `.members` with `.users` if thats the reason.

**Comment by molenzwiebel** [comment]
This is just because Discord.js doesn't guarantee that your local copy of members is 100% accurate by default. My experience with Orianna (which uses eris, but acts similar) is that on average you miss 10-20 members per server. People can get unlucky and not be loaded. You could consider using [Guild.fetchMembers](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchMembers) but it might slow you down ;).
